Add fast deployment
bit-bots/bitbots_main pull request #339
Opened 2024-02-07 15:05 UTC by Flova

# Summary
- Reuses the locally compiled binaries on the robot
- based on #223

## Related issues

## Checklist

- [ ] Run `colcon build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] This PR is on our `Software` project board

2024-04-10 22:58 UTC, texhnolyze requested changes
Hey sorry, I missed that the PR is still a draft.
Feel free to disregard stuff, that is not applicable anymore.

2024-04-10 22:58 UTC, texhnolyze commented on scripts/deploy/deploy_robots.py
> +            help="Don't build/compile on the target machines, instead synchronize the complete install directory from the local machine.",
I would write build/install, as we are syncing both as far as I've seen.

2024-04-10 22:58 UTC, texhnolyze commented on scripts/deploy/deploy_robots.py
> +        parser.add_argument(
I personally would suggest renaming or even skipping the `-f` shorthand, because in a lot of tools `-f` stands for `force` and breaks with general CLI tooling convention.

Also, as long as we are not using the `-f` flag for multiple combined speedup options, I would suggest defining a `dest` with a clear variable name, as with the other arguments.

E.g. `sync_build_alternative` or just `skip_build` or something of the sort.

2024-04-10 22:58 UTC, texhnolyze commented on scripts/deploy/deploy_robots.py
> +        if args.fast:
I think it's generally fine, but now you could theroretically pass both `--build` and `--fast` and get a potentially confusing outcome for the user, as changed files on the robot are also cleaned and no build is happening.

2024-04-10 22:58 UTC, texhnolyze commented on scripts/deploy/tasks/sync.py
> +        self._fast = fast
I think `fast` is especially wrong in a `Sync` class, seeing as the non fast sync includes less files and should actually be faster.

2024-04-10 22:58 UTC, texhnolyze commented on scripts/deploy/tasks/sync.py
> +                    "'--include=+ src/**'",
Could including all `src/**` subfolders lead to later build/execution issues, when things are copied that are not part of our sync includes?

2024-05-02 13:47 UTC, jaagut commented
We don't want to finish this, as the feature "fast deployement" my introduce errors and we can only use this in a few situations. Current methods work sufficiently. We don't need to introduce this additional dirty complexity.

2024-05-02 13:47 UTC, closed without merging