Feature/speak dsd
bit-bots/bitbots_main pull request #411
Opened 2024-04-19 17:47 UTC by JanNiklasFeld

# Summary

## Proposed changes

## Related issues

## Checklist

- [ ] Run `colcon build`
- [ ] Write documentation
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Create issues for future work
- [x] Triage this PR and label it

2024-04-19 20:56 UTC, jaagut requested changes

2024-04-19 20:56 UTC, jaagut commented on bitbots_behavior/bitbots_body_behavior/bitbots_body_behavior/main.dsd
> +            AHEAD --> @Stand + duration:0.5 + r:false, @PlayAnimationCheering + r:false, @PlaySound + file:fanfare.wav, @LookForward, @Stand
Why did you remove the `@ChangeAction + action:waiting`?

2024-04-19 20:56 UTC, jaagut commented on bitbots_behavior/bitbots_body_behavior/bitbots_body_behavior/actions/speak.py
> +        except ImportError:
Please add another exception for `PlaysoundException` if the file can not be found.

2024-04-19 22:07 UTC, JanNiklasFeld commented on bitbots_behavior/bitbots_body_behavior/bitbots_body_behavior/main.dsd
> +            AHEAD --> @Stand + duration:0.5 + r:false, @PlayAnimationCheering + r:false, @PlaySound + file:fanfare.wav, @LookForward, @Stand
Because it changes the action communicated to the other robots. Which should not be necessary anymore after a game.

2024-04-19 22:40 UTC, Flova commented on bitbots_behavior/bitbots_body_behavior/bitbots_body_behavior/actions/speak.py
> +            from playsound import playsound
Why is playsound imported during runtime?

2024-04-19 22:40 UTC, Flova commented
Are the audio files okay licencing wise?

2024-04-20 06:49 UTC, timonegk commented on bitbots_behavior/bitbots_body_behavior/bitbots_body_behavior/actions/speak.py
> +            from playsound import playsound
So that it does not lead to errors during runtime if the library is not available.

2024-04-20 06:49 UTC, timonegk commented
> Are the audio files okay licensing wise?

I added the license of `fanfare.wav`. `ole.wav` is now our own production.

2024-04-20 08:08 UTC, texhnolyze approved these changes

2024-04-20 08:18 UTC, jaagut approved these changes

2024-04-20 08:18 UTC, merged