Fix duplication of team data information in robot filter
bit-bots/bitbots_main pull request #440
Opened 2024-05-02 17:02 UTC by Flova

# Summary
Currently, the poses of the other robots from the team data are added to the robot filter, but they are not deduplicated. Instead, they stack up until a couple of hundred robots are present inside the filter. They are only removed after being in the filter for 10 seconds. This pr changes that, so the team data is only added before we publish the filter result. It does not influence the filter state and a lower timeout of 1 sec is applied, so we don't include team data of robots that have been removed.

# Example

![image](https://github.com/bit-bots/bitbots_main/assets/15075613/3db98dbf-0835-49a3-95f8-d6e02f4d42cc)
This image shows the 10-second trail from the team data of another robot. This should not happen. Instead, it should be a singular point.
This image also shows the team data of a robot that thought it was playing, but it was taken out and not localized. We should be careful with that are wrong team data might mess things up. So we should remember to turn them off if they are taken out.

![image](https://github.com/bit-bots/bitbots_main/assets/15075613/b913a708-2e70-4571-919b-e9661241b059)

I am not really sure how to properly test this. We might need a team data simulator.

2024-05-03 14:59 UTC, texhnolyze requested changes
Is this the correct way to handle this?
If I understand correctly, we add our teammates from the team communication `team data` and then filter by timestamps of when this team data was received.

I see two potential issues with this:
1. We publish team data for each message received from a teammate -> so this would still lead to multiple objects per robot. Is that the behavior we want or would we want to filter by recency or even confidence (which is also available).
2.

2024-05-03 14:59 UTC, texhnolyze commented on bitbots_world_model/bitbots_robot_filter/bitbots_robot_filter/filter.py
> +        # Check if the team data is fresh enough
How about calling the method `is_team_data_fresh` and removing the comment?

2024-05-03 14:59 UTC, texhnolyze commented on bitbots_world_model/bitbots_robot_filter/bitbots_robot_filter/filter.py
> +            return abs((self.get_clock().now() - Time.from_msg(msg.header.stamp)).nanoseconds) < self.team_data_timeout
Any reason to call `abs` here. As far as I'm aware it should never happen, that the current timestamp < than the team data timestamp.
And should this be the case, then do we want to use the team data? In that case it seems more, that there is an issue somewhere else and we would not

2024-05-08 07:33 UTC, Flova commented
We already talked about this in person, but I add it here for completion. The ball filter currently only includes the positions of the team mates via team com. It does not include the robots detected by the team mates. It also does not consider if we or the team mates are localized properly, as we don't have a good way of knowing if this is the case.

2024-05-28 15:58 UTC, texhnolyze approved these changes

2024-05-28 15:58 UTC, merged