Use higher process kf when ball should be visible but is not
bit-bots/bitbots_main pull request #480
Opened 2024-06-13 11:59 UTC by val-ba

# Summary

We want to use a higher process noise if the kf predicts the ball to be in our fov, but we cannot detect it.
## Proposed changes

- Create a subscription on the camera info topic to get the camera matrix
- test whether it is in fov by transforming it into the camera frame and applying the camera matrix
## Related issues

#230
## Checklist

- [ ] Run `colcon build`
- [ ] Write documentation
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Create issues for future work
- [ ] Triage this PR and label it

2024-06-13 17:20 UTC, jaagut commented on bitbots_world_model/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +            return False
I think as a fallback, we should return True. Or if this happens for a short while we wouldn't use an otherwise correct ball detection.

2024-06-13 17:20 UTC, jaagut commented on bitbots_world_model/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +            if 0 < p_pixel[0] <= self.camera_info.width and 0 < p_pixel[1] <= self.camera_info.height:
@Flova is it the case, that YOEO could predict a bounding box with a bottom center point outside the image (e.g. because of knowledge about the ball right at the image edge)? In that case, we would dismiss an otherwise good ball.
Anyway, do we want to add a bit of tolerance here?

2024-06-14 06:39 UTC, Flova commented on bitbots_world_model/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +            return False
I think saying we should not be able to see the ball is the more reasonable fallback here, as it essentially reverts to the old behavior.

2024-06-14 06:41 UTC, Flova commented on bitbots_world_model/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +            return False
We only check if we should see the ball but don't see it. This is all it does. So we don't ignore any balls. It just increases the uncertainty if there is no ball but there should be one.

2024-06-14 06:47 UTC, Flova commented on bitbots_world_model/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +            if 0 < p_pixel[0] <= self.camera_info.width and 0 < p_pixel[1] <= self.camera_info.height:
I agree that we might want to add some border here, but for different reasons. As explained earlier this is not a detection by YOEO, but instead the expected ball position projected into the camera to check if we should see the ball when YOEO detects no ball. In this case the uncertainty would be increased to model the negative observation. I still think that a border makes sense. Just in the other direction. Detections near the image border might not be as reliable, so we should not treat the absence of a detection as a negative observation here. Therefore I would lower the window in image space that is used for negative observations.

2024-06-14 06:52 UTC, Flova requested changes

2024-06-14 06:52 UTC, Flova commented on bitbots_world_model/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +                self.kf.Q = Q_discrete_white_noise(
Process noise is only increased and never decreased.

2024-06-18 07:20 UTC, val-ba commented on bitbots_world_model/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +            if 0 < p_pixel[0] <= self.camera_info.width and 0 < p_pixel[1] <= self.camera_info.height:
So I should apply I threshold?

2024-06-22 10:45 UTC, Flova approved these changes

2024-06-22 10:46 UTC, merged