Feature: publish repo status
bit-bots/bitbots_main pull request #507
Opened 2024-06-27 23:57 UTC by jaagut

# Summary

This publishes the current commit hash (and friendly name) of all repositories.
This also gets recorded into rosbags.

## Proposed changes

- Deploy tool
  - Do repo-checks on `bitbots_main` and allgit-repos as defined in the VCS `workspace.repo` file in parallel
  - Print fancy warnings
  - Write `workspace_status.json` file containing all commit-hashes and friendly names
- `highlevel.launch` launches new node to read `workspace_status.json` file and publish contents as a `String` message
- rosbag-record tool records this message

## Related issues

Closes #443

## Checklist

- [X] Run `colcon build`
- [ ] Write documentation
- [ ] Test on your machine
- [X] Test on the robot
- [ ] Create issues for future work
- [X] Triage this PR and label it

2024-06-28 06:31 UTC, Flova requested changes
Most things are minor issues and up to personal preference, but I think pyyaml should come from rosdep/apt if possible (like it is declared in other nodes requiring it).

2024-06-28 06:31 UTC, Flova commented on bitbots_misc/bitbots_bringup/launch/highlevel.launch
> +                <param name="workspace_status_path" value="$(find-pkg-share bitbots_utils)/config/workspace_status.json"/>
If that file is always in the share of utils, you can just hard code it in Python, as the package share path is available there. It would be slightly less complex, but in the end it really doesn't matter that much.

2024-06-28 06:31 UTC, Flova commented on bitbots_misc/bitbots_utils/scripts/publish_workspace_status.py
> +            self.destroy_node()
Does destroy node terminate the code. Because there is no return after it. So it could be that it just destroys the context, but we keep executing.

2024-06-28 06:31 UTC, Flova commented on bitbots_misc/bitbots_utils/scripts/publish_workspace_status.py
> +    executor = SingleThreadedExecutor()
I think you can use the default executor, which is already present and single threaded, using `rclpy.spin(node)`.

2024-06-28 06:31 UTC, Flova commented on requirements/common.txt
> +PyYAML
I think we mainly used the requirements txt for python things that aren't in apt (or don't have an up to date version there). Consider just adding to the the package XML of Bit-Bots utils.

2024-06-28 06:35 UTC, Flova commented on requirements/common.txt
> +PyYAML
Ohh it's there because of the deploy tool right? Does the deploy tool still support non Ros envs?

But we should pin the version to the apt version in this case so nothing breaks by installing the newer one.

2024-06-28 06:38 UTC, jaagut commented on requirements/common.txt
> +PyYAML
What are Ros envs?

2024-06-28 06:46 UTC, Flova commented on requirements/common.txt
> +PyYAML
Environments without Ros (rosdep, ...).

2024-06-29 08:42 UTC, Flova approved these changes

2024-06-29 08:42 UTC, merged