Feature/gpu system monitor
bit-bots/bitbots_main pull request #619
Opened 2024-11-11 19:37 UTC by HR05

# Summary
 - implement gpu usage percentage in system monitor

## Checklist

- [ ] Run `colcon build`
- [ ] Write documentation
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Create issues for future work
- [ ] Triage this PR and label it

2024-11-11 20:46 UTC, Flova reviewed
The code seems fine, but I have a few additions that would be nice to have :)

2024-11-11 20:46 UTC, Flova commented on bitbots_misc/system_monitor/system_monitor/gpu.py
> +    vram_size = gpu.VRAM  # change VRAM to the real attribute name
I am a bit confused by this comment. Is this a TODO or description of the line?

2024-11-11 20:46 UTC, Flova commented on bitbots_misc/system_monitor/system_monitor/gpu.py
> +    vram_usage = gpu.query_vram_usage()
Currently, this only retrieves the VRAM usage. Are there other metrics indicating GPU utilization available? Maybe things like load or temperature.

Also, an absolute amount of VRAM would be interesting to have in the message.

2024-11-11 20:46 UTC, Flova commented on bitbots_misc/system_monitor/system_monitor/monitor.py
> +    node.declare_parameter("gpu_load_percentage", 80.0)
We need to check if 80% is a good default here. Otherwise, a warning might be triggered during normal operation.

2024-11-14 15:09 UTC, HR05 commented on bitbots_misc/system_monitor/system_monitor/gpu.py
> +    vram_size = gpu.VRAM  # change VRAM to the real attribute name
It's a ToDo, I should state it clearly

2024-11-14 15:13 UTC, HR05 commented on bitbots_misc/system_monitor/system_monitor/gpu.py
> +    vram_usage = gpu.query_vram_usage()
Yes, my plan was to first implement just the VRAM usage and then decide which other metrics could be interesting

2024-11-14 18:02 UTC, Flova requested changes

2024-11-14 18:02 UTC, Flova commented on bitbots_misc/system_monitor/system_monitor/monitor.py
> +        gpu_load, gpu_vram_used, gpu_vram_total, gpu_temperature = gpu.collect_all() if do_gpu else 0
This would fail if do_gou is false, because 0 can not be unpacked

2024-11-14 19:37 UTC, Flova reviewed
Otherwise looks good to me.

2024-11-14 19:37 UTC, Flova commented on bitbots_misc/system_monitor/system_monitor/cpus.py
> +    calculate usage percentage based on busy/total time(load, vram_used, vram_total, temperature)
This seems like a typo

2024-11-14 19:39 UTC, Flova commented on bitbots_misc/system_monitor/system_monitor/gpu.py
> +    vram_usage = gpu.query_vram_usage()
I think the selected ones are fine for now

2024-11-14 20:55 UTC, merged